// state_reactive数据
const state_reactive = {
  shopList: [],
  key: "",
  palletList: [],
  loading: false,
};

// 类目分析table title 数据
const category_table_head = [
  // {
  //     title: "类目名称",
  //     width: '',
  //     align: "center",
  //     dataKey: "category_lv3",
  //     key: "category_lv3",
  //     fixed: true,
  //     unit: "",
  // },
  {
    title: "GMV",
    width: "100",
    align: "center",
    dataKey: "gmv",
    key: "gmv",
    fixed: false,
    unit: "",
  },
  {
    title: "时间进度",
    width: "",
    align: "center",
    dataKey: "target_day_rate",
    key: "target_day_rate",
    fixed: false,
    unit: "",
  },
  {
    title: "GMV达成率",
    width: "100",
    align: "center",
    dataKey: "target_gmv_rate",
    key: "target_gmv_rate",
    fixed: false,
    unit: "",
  },
  {
    title: "GMV目标",
    width: "100",
    align: "center",
    dataKey: "target_gmv",
    key: "target_gmv",
    fixed: false,
    unit: "",
  },
  {
    title: "商品简称",
    width: "",
    align: "center",
    dataKey: "product_name",
    key: "product_name",
    fixed: false,
    unit: "",
  },
];

// 货盘详情table title 数据
const pallet_table_head = [
  {
    title: "本月货盘",
    width: "",
    align: "center",
    dataKey: "pallet",
    key: "pallet",
    fixed: true,
    unit: "",
  },
  {
    title: "累计GMV",
    width: "",
    align: "center",
    dataKey: "month_gmv",
    key: "month_gmv",
    fixed: false,
    unit: "",
  },
  {
    title: "GMV目标",
    width: "",
    align: "center",
    dataKey: "target_gmv",
    key: "target_gmv",
    fixed: false,
    unit: "",
  },
  {
    title: "GMV达成率",
    width: "",
    align: "center",
    dataKey: "target_gmv_rate",
    key: "target_gmv_rate",
    fixed: false,
    unit: "",
  },
  {
    title: "推广花费",
    width: "",
    align: "center",
    dataKey: "spend",
    key: "spend",
    fixed: false,
    unit: "",
  },
  {
    title: "推广预算",
    width: "",
    align: "center",
    dataKey: "monthly_budget",
    key: "monthly_budget",
    fixed: false,
    unit: "",
  },
  {
    title: "推广占比",
    width: "",
    align: "center",
    dataKey: "promotion_percentage",
    key: "promotion_percentage",
    fixed: false,
    unit: "",
  },
  {
    title: "推广目标占比",
    width: "",
    align: "center",
    dataKey: "promotion_target_percentage",
    key: "promotion_target_percentage",
    fixed: false,
    unit: "",
  },
  {
    title: "推广差异",
    width: "",
    align: "center",
    dataKey: "promotion_diff",
    key: "promotion_diff",
    fixed: false,
    unit: "",
  },
  {
    title: "时间进度",
    width: "",
    align: "center",
    dataKey: "time_schedule",
    key: "time_schedule",
    fixed: false,
    unit: "",
  },
  {
    title: "综合ROI",
    width: "",
    align: "center",
    dataKey: "composite_roi",
    key: "composite_roi",
    fixed: false,
    unit: "",
  },
  {
    title: "客单价",
    width: "",
    align: "center",
    dataKey: "customer_unit_price",
    key: "customer_unit_price",
    fixed: false,
    unit: "",
  },
  {
    title: "净利润",
    width: "",
    align: "center",
    dataKey: "profit",
    key: "profit",
    fixed: false,
    unit: "",
  },
  {
    title: "支付人数",
    width: "",
    align: "center",
    dataKey: "paid_buyers",
    key: "paid_buyers",
    fixed: false,
    unit: "",
  },
];

// GMV ·table title 数据
const GMV_table_head = [
  {
    title: "",
    width: "",
    align: "center",
    dataKey: "name",
    key: "name",
    fixed: true,
    unit: "",
  },
  {
    title: "S",
    width: "",
    align: "center",
    dataKey: "S",
    key: "S",
    unit: "",
  },
  {
    title: "A",
    width: "",
    align: "center",
    dataKey: "A",
    key: "A",
    unit: "",
  },
  {
    title: "B",
    width: "",
    align: "center",
    dataKey: "B",
    key: "B",
    unit: "",
  },
  {
    title: "C",
    width: "",
    align: "center",
    dataKey: "C",
    key: "C",
    unit: "",
  },
  {
    title: "D",
    width: "",
    align: "center",
    dataKey: "D",
    key: "D",
    unit: "",
  },
];

// 负责人 table title 数据
const ResponsiblePerson_table_head = [
  // {
  //     title: "负责人",
  //     width: '',
  //     align: "center",
  //     dataKey: "manager",
  //     key: "manager",
  //     fixed: true,
  //     unit: "",
  // },
  {
    title: "GMV",
    width: "100",
    align: "center",
    dataKey: "gmv",
    key: "gmv",
    fixed: false,
    unit: "",
  },
  {
    title: "时间进度",
    width: "",
    align: "center",
    dataKey: "target_day_rate",
    key: "target_day_rate",
    fixed: false,
    unit: "",
  },
  {
    title: "GMV达成率",
    width: "120",
    align: "center",
    dataKey: "target_gmv_rate",
    key: "target_gmv_rate",
    fixed: false,
    unit: "",
  },
  {
    title: "GMV目标",
    width: "100",
    align: "center",
    dataKey: "target_gmv",
    key: "target_gmv",
    fixed: false,
    unit: "",
  },
  {
    title: "经营利润",
    width: "",
    align: "center",
    dataKey: "profit",
    key: "profit",
    fixed: false,
    unit: "",
  },
  {
    title: "利润目标",
    width: "",
    align: "center",
    dataKey: "profit_rate",
    key: "profit_rate",
    fixed: false,
    unit: "",
  },
  {
    title: "利润达成率",
    width: "",
    align: "center",
    dataKey: "profit_target_rate",
    key: "profit_target_rate",
    fixed: false,
    unit: "",
  },
];

// 商品详情 table title 数据
const product_details_table_head = [
  {
    title: "商品ID",
    width: "120",
    align: "center",
    dataKey: "product_id",
    key: "product_id",
    fixed: true,
    unit: "",
  },
  {
    title: "商品简称",
    width: "",
    align: "center",
    dataKey: "product_name",
    key: "product_name",
    fixed: false,
    unit: "",
  },
  {
    title: "GMV",
    width: "",
    align: "center",
    dataKey: "month_gmv",
    key: "month_gmv",
    fixed: false,
    unit: "",
  },
  {
    title: "GMV目标",
    width: "",
    align: "center",
    dataKey: "target_gmv",
    key: "target_gmv",
    fixed: false,
    unit: "",
  },
  {
    title: "GMV达成率",
    width: "100",
    align: "center",
    dataKey: "target_gmv_rate",
    key: "target_gmv_rate",
    fixed: false,
    unit: "",
  },
  {
    title: "推广花费",
    width: "",
    align: "center",
    dataKey: "spend",
    key: "spend",
    fixed: false,
    unit: "",
  },
  {
    title: "推广预算",
    width: "",
    align: "center",
    dataKey: "monthly_budget",
    key: "monthly_budget",
    fixed: false,
    unit: "",
  },
  {
    title: "推广占比",
    width: "",
    align: "center",
    dataKey: "promotion_percentage",
    key: "promotion_percentage",
    fixed: false,
    unit: "",
  },
  {
    title: "推广目标占比",
    width: "120",
    align: "center",
    dataKey: "promotion_target_percentage",
    key: "promotion_target_percentage",
    fixed: false,
    unit: "",
  },
  {
    title: "推广差异",
    width: "",
    align: "center",
    dataKey: "promotion_diff",
    key: "promotion_diff",
    fixed: false,
    unit: "",
  },
  {
    title: "时间进度",
    width: "",
    align: "center",
    dataKey: "target_day_rate",
    key: "target_day_rate",
    fixed: false,
    unit: "",
  },
  {
    title: "综合ROI",
    width: "",
    align: "center",
    dataKey: "composite_roi",
    key: "composite_roi",
    fixed: false,
    unit: "",
  },
  {
    title: "客单价",
    width: "",
    align: "center",
    dataKey: "customer_unit_price",
    key: "customer_unit_price",
    fixed: false,
    unit: "",
  },
  {
    title: "净利润",
    width: "",
    align: "center",
    dataKey: "profit",
    key: "profit",
    fixed: false,
    unit: "",
  },
  {
    title: "支付人数",
    width: "",
    align: "center",
    dataKey: "paid_buyers",
    key: "paid_buyers",
    fixed: false,
    unit: "",
  },
  {
    title: "类目名称",
    width: "",
    align: "center",
    dataKey: "category_lv3",
    key: "category_lv3",
    fixed: false,
    unit: "",
  },
];

export {
  pallet_table_head,
  category_table_head,
  state_reactive,
  GMV_table_head,
  ResponsiblePerson_table_head,
  product_details_table_head,
};
